### ISSUE TITLE
VTYSH_PIMD undeclared

### ISSUE THREAD

**Issue by 39Delta** [udhos/qpimd#4]
During compilation I get an error "vtysh.c:62: error: 'VTYSH_PIMD' undeclared here (not in a function)" so I added a define line to vtysh.h for pimd and want to know what hex value to give it.  I picked an unused value and it compiles and runs.  But when I go into vtysh and run "show ip mroute" I get an error that is as follows "% [RIP] Unknown command: show ip mroute" after the unicast routing table is displayed.  This using the latest pim.2 branch.  Are these two problems related?  

Thanks,

**Comment by donaldsharp** [comment]
I would pull a new version of the tree.  If VTYSH_PIMD is not defined
something has gotten messed up.

donald

**Comment by udhos** [comment]
Are you building like this?

git clone https://github.com/udhos/qpimd
cd qpimd
git checkout pim-only-rebased
autoreconf -i
./configure --enable-pimd
make

Now that pimd is merged into Quagga, have you tried to use the latest official release from Quagga? 
http://download.savannah.gnu.org/releases/quagga/

**Comment by udhos** [comment]
I have confirmed VTYSH_PIMD definition is missing. Fix is:

--- a/vtysh/vtysh.h
+++ b/vtysh/vtysh.h
@@ -30,6 +30,7 @@
 #define VTYSH_BGPD   0x20
 #define VTYSH_ISISD  0x40
 #define VTYSH_BABELD  0x80
+#define VTYSH_PIMD   0x100
 #define VTYSH_ALL        VTYSH_ZEBRA|VTYSH_RIPD|VTYSH_RIPNGD|VTYSH_OSPFD|VTYSH_OSPF6D|VTYSH_BGPD|VTYSH_ISISD|VTYSH_BABELD|VTYSH_PIMD
 #define VTYSH_RMAP       VTYSH_ZEBRA|VTYSH_RIPD|VTYSH_RIPNGD|VTYSH_OSPFD|VTYSH_OSPF6D|VTYSH_BGPD|VTYSH_BABELD
 #define VTYSH_INTERFACE          VTYSH_ZEBRA|VTYSH_RIPD|VTYSH_RIPNGD|VTYSH_OSPFD|VTYSH_OSPF6D|VTYSH_ISISD|VTYSH_BABELD|VTYSH_PIMD

However it is already fixed in official Quagga.

**Comment by udhos** [comment]
Fixed in https://github.com/udhos/qpimd/commit/3585b388ada59a6b3eb48876f3fe672f9e23ac4c
But please notice this was already fixed in official Quagga.

**Comment by 39Delta** [comment]
OMG I did not even notice that a new release was dropped.  Checking it out now.  Also your commit fixed my issue and the vtysh commands work.

Thanks for the great work,
